server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 2000
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate # или update, create, create-drop, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect